{% set name = "jupyter-launcher-shortcuts" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_launcher_shortcuts-{{ version }}.tar.gz
  sha256: 147631fcaecb2c00a175cf92526fd32702959e2b93fc6609f8fd679536be9ff8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - hatch-jupyter-builder >=0.9.1
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_server
    - jupyterlab >=4,<5
    - tornado
    - traitlets

test:
  imports:
    - jupyter_launcher_shortcuts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/2i2c-org/jupyter-launcher-shortcuts
  summary: Provide arbitrary shortcuts for apps in JupyterLab
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - labextension/LICENSE

extra:
  recipe-maintainers:
    - maresb
