{% set name = "jupyter-launcher-shortcuts" %}
{% set version = "4.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 147631fcaecb2c00a175cf92526fd32702959e2b93fc6609f8fd679536be9ff8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - aiohttp
    - notebook
    - python >=3.5
    - simpervisor

test:
  imports:
    - jupyter_launcher_shortcuts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yuvipanda/jupyter-launcher-shortcuts
  summary: Easily place shortcuts
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
